services:
  petboarding_api:
    image: ${DOCKER_REGISTRY-}petboardingapi
    container_name: petboarding.api
    build:
      context: ..
      dockerfile: Core_PetBoarding_Backend/PetBoarding_Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Host=postgres.database;Port=5432;Database=petboarding;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=petboarding
      - RabbitMQ__Password=petboarding123
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__ExchangeName=petboarding.events
      - JAEGER_ENDPOINT=http://jaeger:4317
      - SEQ_URL=http://seq
      - OTEL_SERVICE_NAME=PetBoarding.Api
    ports:
      - '5000:5000'
      - '5001:5001'
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro
    depends_on:
      postgres.database:
        condition: service_healthy
      memcached:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
      seq:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network
      - database-network
      - cache-network
      - messaging-network
      - observability-network

  petboarding_taskworker:
    image: ${DOCKER_REGISTRY-}petboardingtaskworker
    container_name: petboarding.taskworker
    build:
      context: ..
      dockerfile: Core_PetBoarding_Backend/PetBoarding_TaskWorker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres.database;Port=5432;Database=petboarding;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=petboarding
      - RabbitMQ__Password=petboarding123
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__ExchangeName=petboarding.events
      - TaskWorker__ExpiredBasketCleanupIntervalMinutes=10
      - TaskWorker__BasketExpirationMinutes=30
      - TaskWorker__ExpiredReservationProcessingIntervalMinutes=15
      - JAEGER_ENDPOINT=http://jaeger:4317
      - SEQ_URL=http://seq
      - OTEL_SERVICE_NAME=PetBoarding.TaskWorker
    depends_on:
      petboarding_api:
        condition: service_started
      postgres.database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
      seq:
        condition: service_started
    restart: unless-stopped
    deploy:
      replicas: 1
    networks:
      - app-network
      - database-network
      - messaging-network
      - observability-network

  postgres.database:
    image: postgres:17-alpine
    container_name: petboarding.postgres.database
    hostname: postgres.database
    environment:
      - POSTGRES_DB=petboarding
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/petboarding-db:/var/lib/postgresql/data
      - ./PetBoarding_TaskWorker/init-quartz.sql:/docker-entrypoint-initdb.d/init-quartz.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d petboarding']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - database-network

  memcached:
    image: memcached:1.6.32-alpine
    container_name: petboarding.memcached
    hostname: memcached
    command: memcached -m 256 -p 11211 -u memcache -l 0.0.0.0
    ports:
      - '11211:11211'
    restart: unless-stopped
    networks:
      - cache-network

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: petboarding.rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: petboarding
      RABBITMQ_DEFAULT_PASS: petboarding123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI
    volumes:
      - ./.containers/rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - messaging-network

  jaeger:
    image: jaegertracing/all-in-one:1.73.0
    container_name: petboarding.jaeger
    hostname: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_DISABLED=false
    ports:
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
    volumes:
      - ./.containers/jaeger-data:/badger
    restart: unless-stopped
    networks:
      - observability-network

  seq:
    image: datalust/seq:2025.2
    container_name: petboarding.seq
    hostname: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=petboarding123
    ports:
      - '5341:80' # Seq UI and API
      - '5342:5341' # Seq ingestion only
    volumes:
      - ./.containers/seq-data:/data
    restart: unless-stopped
    networks:
      - observability-network

networks:
  app-network:
    driver: bridge
  database-network:
    driver: bridge
  cache-network:
    driver: bridge
  messaging-network:
    driver: bridge
  observability-network:
    driver: bridge

volumes:
  petboarding-db:
    driver: local
    name: petboarding_postgres_data
