services:
  petboarding_api:
    image: ${DOCKER_REGISTRY-}petboardingapi
    container_name: petboarding.api
    build:
      context: .
      dockerfile: PetBoarding_Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - '5000:5000'
      - '5001:5001'
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro
    depends_on:
      postgres.database:
        condition: service_healthy
      memcached:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  petboarding_taskworker:
    image: ${DOCKER_REGISTRY-}petboardingtaskworker
    container_name: petboarding.taskworker
    build:
      context: .
      dockerfile: PetBoarding_TaskWorker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=petboarding.postgres.database:5432;Database=petboarding;Username=postgres;Password=postgres
      - TaskWorker__ExpiredBasketCleanupIntervalMinutes=10
      - TaskWorker__BasketExpirationMinutes=30
      - TaskWorker__ExpiredReservationProcessingIntervalMinutes=15
    depends_on:
      postgres.database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 1

  postgres.database:
    image: postgres:latest
    container_name: petboarding.postgres.database
    environment:
      - POSTGRES_DB=petboarding
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/petboarding-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d petboarding']
      interval: 5s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached:latest
    container_name: petboarding.memcached
    command: memcached -m 256 -p 11211 -u memcache -l 0.0.0.0
    ports:
      - "11211:11211"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: petboarding.rabbitmq
    hostname: petboarding-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: petboarding
      RABBITMQ_DEFAULT_PASS: petboarding123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - ./.containers/rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
